// Code generated by @black-atom/core. DO NOT EDIT.
package theme

func init() {
	Register(Theme{
		Key:        "black-atom-paper-blue-dark",
		Appearance: "dark",

		BgSelection: "#283b67",
		BgContrast:  "#d1d8e5",
		BgNegative:  "#623e3e",

		FgDefault:  "#ebf2ff",
		FgSubtle:   "#8098ca",
		FgAccent:   "#fa8f19",
		FgDisabled: "#6379aa",
		FgContrast: "#152650",
		FgNegative: "#dd7577",
		FgInfo:     "#79b5cc",
		FgAdd:      "#a9ba78",
		FgDelete:   "#dd7577",

		PaletteYellow:      "#8098ca",
		PaletteGreen:       "#8098ca",
		PaletteRed:         "#9eb7eb",
		PaletteBlue:        "#9eb7eb",
		PaletteMagenta:     "#8098ca",
		PaletteDarkMagenta: "#8098ca",
	})
}
