// Code generated by @black-atom/core. DO NOT EDIT.
package theme

func init() {
	Register(Theme{
		Key:        "black-atom-paper-blue-light",
		Appearance: "light",

		BgSelection: "#dbdee5",
		BgContrast:  "#153bb7",
		BgNegative:  "#ffd3cf",

		FgDefault:  "#040089",
		FgSubtle:   "#2955d3",
		FgAccent:   "#275bff",
		FgDisabled: "#497cfd",
		FgContrast: "#e4e8ef",
		FgNegative: "#f14d4c",
		FgInfo:     "#00a3e9",
		FgAdd:      "#819e00",
		FgDelete:   "#f14d4c",

		PaletteYellow:      "#497cfd",
		PaletteGreen:       "#497cfd",
		PaletteRed:         "#5a8fff",
		PaletteBlue:        "#5a8fff",
		PaletteMagenta:     "#497cfd",
		PaletteDarkMagenta: "#497cfd",
	})
}
